version: '3.8'

services:
  php:
    build:
      context: ./back
      dockerfile: ../docker/php/Dockerfile
    container_name: php
    volumes:
      - ./back:/var/www

  server:
    image: nginx:alpine
    container_name: server
    ports:
      - "8000:80"
    volumes:
      - ./back:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  ui:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: ui
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
