version: '3.8'

services:
  php:
    build:
      context: ./back
      dockerfile: ../docker/php/Dockerfile
    container_name: php
    volumes:
      - ./back:/var/www

  queue-worker:
    build:
      context: ./back
      dockerfile: ../docker/php/Dockerfile
    container_name: queue-worker
    command: php artisan queue:work --sleep=3 --tries=1
    volumes:
      - ./back:/var/www
    depends_on:
      - php

  server:
    image: nginx:alpine
    container_name: server
    ports:
      - "9100:80"
    volumes:
      - ./back:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  ui:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:9100/api
    container_name: ui
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
